CREATE DATABASE PROGRAMS;
USE PROGRAMS;

CREATE TABLE STUDENT(NAME VARCHAR(220),REGNUMBER INT PRIMARY KEY,EMAIL VARCHAR(220),PHONE VARCHAR(220));


CREATE TABLE INSTRUCTOR(NAME VARCHAR(220),EMPID INT,EMAIL VARCHAR(220),DESIGNATION VARCHAR(220),PHONE VARCHAR(220));

CREATE TABLE COURSE(NAME VARCHAR(220),COURSEID VARCHAR(220),CONTACTHOURS VARCHAR(220),INSTID INT
);

CREATE TABLE TAKE(STUDENTID INT,COURSEID VARCHAR(220),GRADE VARCHAR(220));


INSERT INTO STUDENT VALUES('JHON',001,'JHON@GMAIL.COM','5478965412');

INSERT INTO STUDENT VALUES( 'LUCAS',002,'LUCAS@GMAIL.COM','7854123658');


INSERT INTO INSTRUCTOR VALUES('MILES',401,'MILES@GMAIL.COM','PROFESSOR','8254632145');

INSERT INTO INSTRUCTOR VALUES('KHABY',402,'KHABY@GMAIL.COM','LAB INSTRUCTOR','9564123585');



INSERT INTO COURSE VALUES('BDA','BD1','2 HOURS',1);

INSERT INTO COURSE VALUES('CC','CC2','3 HOURS',2);



INSERT INTO TAKE VALUES(1001,'BD1','A');

INSERT INTO TAKE VALUES(1002,'CC2','B');

CREATE TABLE NEWCOURSE LIKE COURSE;

INSERT INTO NEWCOURSE SELECT * FROM COURSE;

